@url = https://obscure-palm-tree-9v4vq97w4xjh9xrx-8080.app.github.dev

GET {{url}}/livros

###
GET {{url}}/livros/3

###
POST {{url}}/livros
Content-Type: application/json

{
    "titulo": "Metamorfose",
    "id_genero" : 1,
    "autores" : [{"id": 1}]
}

###
PUT {{url}}/livros/5
Content-Type: application/json

{
    "titulo" : "Livro 5 Alterado",
    "generos" : "Genero Alterado",
    "autores" : "Autor Alterado"
}

###
DELETE {{url}}/livros/5